// LOCAL
/*
var conf = {
  httpProvider: 'http://127.0.0.1:9545',
  abi: [{"constant":false,"inputs":[{"name":"accountIdName","type":"string"},{"name":"ttIndex","type":"uint256"}],"name":"getPlace","outputs":[{"name":"title","type":"string"},{"name":"desc","type":"string"},{"name":"imageLink","type":"string"},{"name":"lat","type":"uint32"},{"name":"lng","type":"uint32"},{"name":"zoom","type":"uint8"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"accountIdName","type":"string"}],"name":"accountExist","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"accountIdName","type":"string"},{"name":"ttIndex","type":"uint256"},{"name":"title","type":"string"},{"name":"desc","type":"string"},{"name":"imageLink","type":"string"},{"name":"lat","type":"uint32"},{"name":"lng","type":"uint32"},{"name":"zoom","type":"uint8"}],"name":"setPlace","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"accountIdName","type":"string"}],"name":"getAccount","outputs":[{"name":"owner","type":"string"},{"name":"desc","type":"string"},{"name":"","type":"bool"},{"name":"lat","type":"uint32"},{"name":"lng","type":"uint32"},{"name":"zoom","type":"uint8"},{"name":"placesNumber","type":"uint256"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"accountIdName","type":"string"},{"name":"ttIndex","type":"uint256"}],"name":"deletePlace","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"accountIdName","type":"string"},{"name":"desc","type":"string"},{"name":"clusterize","type":"bool"},{"name":"lat","type":"uint32"},{"name":"lng","type":"uint32"},{"name":"zoom","type":"uint8"}],"name":"setAccount","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"accountIdName","type":"string"}],"name":"isOwner","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"accountIdName","type":"string"}],"name":"listPlaceIndex","outputs":[{"name":"placesIndex","type":"uint256[]"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"accountIdName","type":"string"}],"name":"accountHash","outputs":[{"name":"","type":"bytes32"}],"payable":false,"stateMutability":"nonpayable","type":"function"}],
  contractAddress: '0x0846F926C9Afc49E52dC24bBA32f1c41487F643F',
  defaultGasLimit: 0
};*/

// ROPSTEN testnet on INFURA
var conf = {
  httpProvider: 'https://ropsten.infura.io/v3/2dad8e8275d24f00ad1f5985b4bf1ba6',
  wssProvider: 'wss://ropsten.infura.io/ws',
  abi: [{"constant":false,"inputs":[{"name":"accountIdName","type":"string"},{"name":"ttIndex","type":"uint256"}],"name":"getPlace","outputs":[{"name":"title","type":"string"},{"name":"desc","type":"string"},{"name":"imageLink","type":"string"},{"name":"lat","type":"uint32"},{"name":"lng","type":"uint32"},{"name":"zoom","type":"uint8"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"accountIdName","type":"string"}],"name":"accountExist","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"accountIdName","type":"string"},{"name":"ttIndex","type":"uint256"},{"name":"title","type":"string"},{"name":"desc","type":"string"},{"name":"imageLink","type":"string"},{"name":"lat","type":"uint32"},{"name":"lng","type":"uint32"},{"name":"zoom","type":"uint8"}],"name":"setPlace","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"accountIdName","type":"string"}],"name":"getAccount","outputs":[{"name":"owner","type":"string"},{"name":"desc","type":"string"},{"name":"","type":"bool"},{"name":"lat","type":"uint32"},{"name":"lng","type":"uint32"},{"name":"zoom","type":"uint8"},{"name":"placesNumber","type":"uint256"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"accountIdName","type":"string"},{"name":"ttIndex","type":"uint256"}],"name":"deletePlace","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"accountIdName","type":"string"},{"name":"desc","type":"string"},{"name":"clusterize","type":"bool"},{"name":"lat","type":"uint32"},{"name":"lng","type":"uint32"},{"name":"zoom","type":"uint8"}],"name":"setAccount","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"accountIdName","type":"string"}],"name":"isOwner","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"accountIdName","type":"string"}],"name":"listPlaceIndex","outputs":[{"name":"placesIndex","type":"uint256[]"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"accountIdName","type":"string"}],"name":"accountHash","outputs":[{"name":"","type":"bytes32"}],"payable":false,"stateMutability":"nonpayable","type":"function"}],
  contractAddress: '0x3bB2523a67772A30805bC6C65443Df5Dd61e7355',
  defaultGasLimit: 0,
  currentNetworkId: 3 // 3:ropsten
};

 // ROPSTEN LOCAL
/*
var conf = {
  httpProvider: 'http://127.0.0.1:8545',
  abi: [{"constant":false,"inputs":[{"name":"accountIdName","type":"string"},{"name":"ttIndex","type":"uint256"}],"name":"getPlace","outputs":[{"name":"title","type":"string"},{"name":"desc","type":"string"},{"name":"imageLink","type":"string"},{"name":"lat","type":"uint32"},{"name":"lng","type":"uint32"},{"name":"zoom","type":"uint8"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"accountIdName","type":"string"}],"name":"accountExist","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"accountIdName","type":"string"},{"name":"ttIndex","type":"uint256"},{"name":"title","type":"string"},{"name":"desc","type":"string"},{"name":"imageLink","type":"string"},{"name":"lat","type":"uint32"},{"name":"lng","type":"uint32"},{"name":"zoom","type":"uint8"}],"name":"setPlace","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"accountIdName","type":"string"}],"name":"getAccount","outputs":[{"name":"owner","type":"string"},{"name":"desc","type":"string"},{"name":"","type":"bool"},{"name":"lat","type":"uint32"},{"name":"lng","type":"uint32"},{"name":"zoom","type":"uint8"},{"name":"placesNumber","type":"uint256"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"accountIdName","type":"string"},{"name":"ttIndex","type":"uint256"}],"name":"deletePlace","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"accountIdName","type":"string"},{"name":"desc","type":"string"},{"name":"clusterize","type":"bool"},{"name":"lat","type":"uint32"},{"name":"lng","type":"uint32"},{"name":"zoom","type":"uint8"}],"name":"setAccount","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"accountIdName","type":"string"}],"name":"isOwner","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"accountIdName","type":"string"}],"name":"listPlaceIndex","outputs":[{"name":"placesIndex","type":"uint256[]"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"accountIdName","type":"string"}],"name":"accountHash","outputs":[{"name":"","type":"bytes32"}],"payable":false,"stateMutability":"nonpayable","type":"function"}],
  contractAddress: '0x3bB2523a67772A30805bC6C65443Df5Dd61e7355',
  defaultGasLimit: 0
};*/
